# Generated by Django 2.2.2 on 2019-06-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to="sponsors", verbose_name="CI로고"
            ),
        ),
    ]
