# Generated by Django 2.2.2 on 2019-07-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0003_auto_20190724_2131"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsortier",
            options={
                "ordering": ("-seminar", "order"),
                "verbose_name": "스폰서 등급",
                "verbose_name_plural": "스폰서 등급 목록",
            },
        ),
        migrations.AddField(
            model_name="sponsortier",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="순서"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="tier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsor_set",
                to="sponsors.SponsorTier",
                verbose_name="등급",
            ),
        ),
    ]
