# Generated by Django 2.2.2 on 2019-07-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0004_auto_20190724_2136"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsortier",
            options={
                "ordering": ("order",),
                "verbose_name": "스폰서 등급",
                "verbose_name_plural": "스폰서 등급 목록",
            },
        ),
    ]
