# Generated by Django 3.1 on 2020-08-26 11:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0006_auto_20190728_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="logo_white",
            field=models.FileField(
                blank=True, upload_to="sponsors", verbose_name="CI로고 (흰색)"
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="logo_white_bgcolor",
            field=colorfield.fields.ColorField(default="#72a0e0", max_length=18),
        ),
    ]
