repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace

      - id: check-yaml
        exclude: .*docker-compose.*?y(am|m)l

      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: make-dockerfile
        name: Make Dockerfile.deploy
        language: system
        entry: bash -c '
          .scripts/make_dockerfile.py &&
          git add Dockerfile.deploy'
        files: Dockerfile|.scripts/make_dockerfile.py

      - id: poetry-export
        name: Poetry export requirements
        language: system
        description: Poetry export requirements.txt
        entry: bash -c '
          poetry export --without-hashes -o requirements.txt &&
          poetry export --without-hashes --dev -o requirements_dev.txt &&
          git add requirements*.txt'
        files: pyproject.toml|poetry.lock
