version: '2.4'

services:
  web:
    image: "347809506342.dkr.ecr.ap-northeast-2.amazonaws.com/letusgo:django"
    restart: always
    command: >
      bash -c "python3 manage.py collectstatic --noinput &&
      gunicorn config.wsgi.production:application --bind 0.0.0.0:8000 --chdir /srv/project/app --access-logfile /var/log/gunicorn-access.log --error-logfile /var/log/gunicorn-error.log"
    expose:
      - 8000
    volumes:
      - static:/srv/project/.static
    mem_limit: 400m

  nginx:
    image: azelf/letusgo:nginx
    restart: always
    volumes:
      - static:/srv/project/.static
    ports:
      - 80:80
    mem_limit: 300m
    depends_on:
      - web

volumes:
  static:
