version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

#  django_dev:
#    build:
#      context: https://github.com/LeeHanYeong/let-us-Go.git#develop
#      dockerfile: Dockerfile
#    expose:
#      - '8001'
#    command: gunicorn -c /srv/.config/gunicorn_dev.py config.wsgi.production_dev
