version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - static-feature:/srv/feature/.static
      - static-dev:/srv/dev/.static
      - static-master:/srv/master/.static
    ports:
      - '80:80'
      - '443:443'

  django_feature:
    build:
      context: https://github.com/LeeHanYeong/let-us-Go.git#feature
      dockerfile: Dockerfile
      args:
        requirements: requirements_dev.txt
        gunicorn: /srv/.config/gunicorn_feature.py
        wsgi: config.wsgi.production_dev
        settings: config.settings.production_dev
    volumes:
      - static-feature:/srv/.static
    expose:
      - '8002'
    env_file:
      - .env

  django_develop:
    build:
      context: https://github.com/LeeHanYeong/let-us-Go.git#develop
      dockerfile: Dockerfile
      args:
        requirements: requirements_dev.txt
        gunicorn: /srv/.config/gunicorn_dev.py
        wsgi: config.wsgi.production_dev
        settings: config.settings.production_dev
    volumes:
      - static-dev:/srv/.static
    expose:
      - '8001'
    env_file:
      - .env

  django_master:
    build:
      context: https://github.com/LeeHanYeong/let-us-Go.git#master
      dockerfile: Dockerfile
      args:
        requirements: requirements.txt
        gunicorn: /srv/.config/gunicorn_master.py
        wsgi: config.wsgi.production_master
        settings: config.settings.production_master
    volumes:
      - static-master:/srv/.static
    expose:
      - '8000'
    env_file:
      - .env

volumes:
  static-feature:
  static-dev:
  static-master:
