version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '8080:80'
      - '443:443'

  django_dev:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '8001'
    env_file:
      - .env
    command: gunicorn -c /srv/.config/gunicorn_dev.py config.wsgi.production_dev
