version: '3'

services:
  letusgo:
    image: nginx:alpine
    volumes:
      - .deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-dev:/srv/dev/.static
      - static-master:/srv/master/.static
    networks:
      - default
      - proxy

  django_develop:
    build:
      context: https://github.com/LeeHanYeong/let-us-Go.git#develop
      dockerfile: Dockerfile.deploy
      args:
        requirements: requirements_dev.txt
        gunicorn: /srv/.deploy/gunicorn_dev.py
        wsgi: config.wsgi.production_dev
        settings: config.settings.production_dev
    volumes:
      - static-dev:/srv/.static
    env_file:
      - .env
    networks:
      - default

  django_master:
    build:
      context: https://github.com/LeeHanYeong/let-us-Go.git#master
      dockerfile: Dockerfile.deploy
      args:
        requirements: requirements.txt
        gunicorn: /srv/.deploy/gunicorn_master.py
        wsgi: config.wsgi.production_master
        settings: config.settings.production_master
    volumes:
      - static-master:/srv/.static
    env_file:
      - .env
    networks:
      - default

volumes:
  static-dev:
  static-master:

networks:
  default:
  proxy:
    external: true
