version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .config/nginx_dev.conf:/etc/nginx/conf.d/default.conf
      - static-feature:/srv/feature/.static
      - static-dev:/srv/dev/.static
      - static-master:/srv/master/.static
    ports:
      - '80:80'
      - '8080:80'
      - '443:443'

  django_feature:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements: requirements_dev.txt
        gunicorn: /srv/.config/gunicorn_dev.py
        wsgi: config.wsgi.production_dev
        settings: config.settings.production_dev
    volumes:
      - static-feature:/srv/.static
    env_file:
      - .env

  django_develop:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements: requirements_dev.txt
        gunicorn: /srv/.config/gunicorn_dev.py
        wsgi: config.wsgi.production_dev
        settings: config.settings.production_dev
    volumes:
      - static-dev:/srv/.static
    env_file:
      - .env

  django_master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements: requirements.txt
        gunicorn: /srv/.config/gunicorn_master.py
        wsgi: config.wsgi.production_master
        settings: config.settings.production_master
    volumes:
      - static-master:/srv/.static
    env_file:
      - .env

volumes:
  static-feature:
  static-dev:
  static-master:
