# Generated by Django 2.2.2 on 2019-06-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seminars", "0003_auto_20190627_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("low", "초급"), ("mid", "중급"), ("high", "고급")],
                max_length=5,
                verbose_name="레벨",
            ),
        ),
    ]
