# Generated by Django 2.2.2 on 2019-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seminars", "0016_speakerlink_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="seminar",
            name="year",
            field=models.IntegerField(blank=True, null=True, verbose_name="연도"),
        ),
    ]
