# Generated by Django 2.2.2 on 2019-07-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_emailvalidation_is_send_success"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailValidation",
            new_name="EmailVerification",
        ),
    ]
