# Generated by Django 3.1 on 2020-08-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_auto_20190701_1511"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_deleted",),
    ]
