# Generated by Django 3.1 on 2020-08-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_auto_20200826_2035"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="type",
            field=models.CharField(
                choices=[("signup", "회원가입 이메일 인증"), ("password_rest", "비밀번호 찾기 인증")],
                default="signup",
                max_length=20,
                verbose_name="유형",
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["type"], name="members_ema_type_599316_idx"),
        ),
    ]
