# Generated by Django 3.1 on 2020-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0016_auto_20200831_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="type",
            field=models.CharField(
                choices=[("signup", "회원가입 이메일 인증"), ("password_reset", "비밀번호 찾기 인증")],
                default="signup",
                max_length=20,
                verbose_name="유형",
            ),
        ),
    ]
