# Generated by Django 3.1 on 2020-10-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0018_auto_20200901_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("kakao", "카카오"),
                    ("facebook", "페이스북"),
                    ("apple", "애플"),
                    ("email", "이메일"),
                ],
                default="email",
                max_length=10,
                verbose_name="유형",
            ),
        ),
    ]
