from django_secrets import SECRETS

# django-aws-secrets-manager
AWS_SECRETS_MANAGER_SECRET_NAME = "lhy"
AWS_SECRETS_MANAGER_PROFILE = "lhy-secrets-manager"
AWS_SECRETS_MANAGER_SECRET_SECTION = "letusgo:base"
AWS_SECRETS_MANAGER_REGION_NAME = "ap-northeast-2"
SECRET_KEY = SECRETS["SECRET_KEY"]

# django-storages
AWS_S3_ACCESS_KEY_ID = SECRETS["AWS_S3_ACCESS_KEY_ID"]
AWS_S3_SECRET_ACCESS_KEY = SECRETS["AWS_S3_SECRET_ACCESS_KEY"]
AWS_S3_FILE_OVERWRITE = SECRETS["AWS_S3_FILE_OVERWRITE"]
AWS_S3_REGION_NAME = "ap-northeast-2"
AWS_DEFAULT_ACL = SECRETS["AWS_DEFAULT_ACL"]
AWS_BUCKET_ACL = SECRETS["AWS_BUCKET_ACL"]
AWS_AUTO_CREATE_BUCKET = SECRETS["AWS_AUTO_CREATE_BUCKET"]

# Email
EMAIL_HOST = SECRETS["EMAIL_HOST"]
EMAIL_HOST_USER = SECRETS["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = SECRETS["EMAIL_HOST_PASSWORD"]
EMAIL_PORT = SECRETS["EMAIL_PORT"]
EMAIL_USE_SSL = SECRETS["EMAIL_USE_SSL"]
DEFAULT_FROM_EMAIL = SECRETS["DEFAULT_FROM_EMAIL"]
