name: CI

on:
  push:
    branches:
      - develop
      - master

env:
  AWS_SECRETS_MANAGER_ACCESS_KEY_ID: ${{ secrets.AWS_SECRETS_MANAGER_ACCESS_KEY_ID }}
  AWS_SECRETS_MANAGER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETS_MANAGER_SECRET_ACCESS_KEY }}
  AWS_ROUTE53_ACCESS_KEY_ID: ${{ secrets.AWS_ROUTE53_ACCESS_KEY_ID }}
  AWS_ROUTE53_SECRET_ACCESS_KEY: ${{ secrets.AWS_ROUTE53_SECRET_ACCESS_KEY }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set env
      run: |
        branch=${GITHUB_REF##*/}
        echo ::set-env name=BRANCH::$branch

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest-cov
      run: pytest --cov app

    - name: Codecov
      run: codecov

    - name: Deploy EC2 docker-compose
      uses: peterkimzz/aws-ssm-send-command@1.0.4
      id: ssm
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_SSM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SSM_SECRET_ACCESS_KEY }}
        instance-ids: |
          ${{ secrets.AWS_INSTANCE_ID }}

        working-directory: /home/ubuntu/let-us-go
        command: sudo -H -u ubuntu bash -c 'python3 update.py ${{ env.BRANCH }}'
        comment: Executed by Github Actions
