name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        branch=${GITHUB_REF##*/}
        echo "BRANCH=$branch" >> $GITHUB_ENV

    - name: Deploy EC2 docker-compose
      uses: peterkimzz/aws-ssm-send-command@1.0.4
      id: ssm
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_SSM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SSM_SECRET_ACCESS_KEY }}
        instance-ids: |
          ${{ secrets.AWS_INSTANCE_ID }}

        working-directory: /home/lhy/projects/letusgo/backend
        command: sudo -H -u ubuntu bash -c 'python3 update.py ${{ env.BRANCH }}'
        comment: Executed by Github Actions
